{{- if default "" .Values.externalUrl }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "gitlab.fullname" . }}
    spec:
      containers:
      - name: {{ template "gitlab.fullname" . }}
        image: {{ template "gitlab.image" . }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab_omnibus_config
        {{- if default "" .Values.postReconfigureScript }}
        - name: GITLAB_POST_RECONFIGURE_SCRIPT
          value: "/bin/bash /scripts/post_reconfigure_script"
        {{- end }}
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        ## DB configuration
        ##
        - name: DB_HOST
          value: {{ template "gitlab.dbHost" . }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: db-password
        - name: DB_DATABASE
          value: {{ template "gitlab.dbDatabase" . }}
        ## Redis configuration
        ##
        - name: REDIS_HOST
          value: {{ template "gitlab.redisHost" . }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: redis-password
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: registry
          containerPort: 8105
        - name: mattermost
          containerPort: 8065
        - name: workhorse
          containerPort: 8005
        - name: prometheus
          containerPort: 9090
        - name: node-exporter
          containerPort: 9100
        livenessProbe:
          httpGet:
            path: /help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 200
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        {{- if default "" .Values.postReconfigureScript }}
        - name: scripts
          mountPath: /scripts
        {{- end }}
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /gitlab-data
        - name: gitlab-registry
          mountPath: /gitlab-registry
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      {{- if default "" .Values.postReconfigureScript }}
      - name: scripts
        configMap:
          name: {{ template "gitlab.fullname" . }}-scripts
      {{- end }}
      - name: gitlab-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab.fullname" . }}-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-data
      {{- if .Values.persistence.gitlabData.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-registry
      {{- if .Values.persistence.gitlabRegistry.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab.fullname" . }}-registry
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ else }}
{{ end }}
