{{- if .Values.adminService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador.fullname" . }}-admin
  labels:
    app: {{ template "ambassador.name" . }}
    chart: {{ template "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ambassador_admin_mapping
      prefix: /ambassador-admin/
      service: {{ template "ambassador.fullname" . }}-admin.ingress-system
spec:
  type: {{ .Values.adminService.type }}
  ports:
    - port: 8877
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: {{ template "ambassador.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
