apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ambassador.fullname" . }}
  labels:
    app: {{ template "ambassador.name" . }}
    chart: {{ template "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ambassador.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ambassador.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      serviceAccountName: {{ template "ambassador.serviceAccountName" . }}
      containers:
        - name: statsd-sink
          image: "{{ .Values.exporter.image }}"
          ports:
          - name: metrics
            containerPort: 9102
        - name: ambassador
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8877
          env:
          - name: AMBASSADOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: AMBASSADOR_RESTART_TIME
            value: {{ .Values.timing.restart | quote }}
          - name: AMBASSADOR_DRAIN_TIME
            value: {{ .Values.timing.drain | quote }}
          - name: AMBASSADOR_SHUTDOWN_TIME
            value: {{ .Values.timing.shutdown | quote }}
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
