apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.project.name }}-{{ .Values.project.stage }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.project.name }}-{{ .Values.project.stage }}-role"
  labels:
    app: "{{ .Values.project.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  namespace: "{{ .Values.project.name }}-{{ .Values.project.stage }}"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.project.name }}-binding"
  namespace: "{{ .Values.project.name }}-{{ .Values.project.stage }}"
  labels:
    app: "{{ .Values.project.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.project.name }}-{{ .Values.project.stage }}-role"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.project.name }}-{{ .Values.project.stage }}-account"
  namespace: "{{ .Values.project.name }}-{{ .Values.project.stage }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.project.name }}-{{ .Values.project.stage }}-account"
  namespace: "{{ .Values.project.name }}-{{ .Values.project.stage }}"
  labels:
    app: "{{ .Values.project.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
automountServiceAccountToken: true
