apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wekan.fullname" . }}
  labels:
    app: {{ template "wekan.name" . }}
    chart: {{ template "wekan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- with .Values.mongoUrl }}
  mongo-url: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.mongoOplogUrl }}
  mongo-oplog-url: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.mailUrl }}
  mail-url: {{ . | b64enc | quote }}
  {{- end }}
