replicaCount: 1
image:
  repository: your.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: secrets-registry
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 8080
  internalPort: 8080
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
