apiVersion: batch/v1
kind: Job
metadata: 
  name: {{ template "grafana.fullname" . }}-chown-backup-directory
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ template "grafana.fullname" . }}-chown-backup-directory
        command: [chown,"472:472", /var/lib/grafana/backups]
        image: busybox:latest
        volumeMounts:
        - name: {{ template "grafana.fullname" . }}-backup
          mountPath: /var/lib/grafana/backups
      volumes:
        {{- if .Values.backup.rawNfsPersistent }}
        - name: {{ template "grafana.fullname" . }}-backup
          nfs:
            path: {{ .Values.backup.rawNfsPath }}
            server: {{ .Values.backup.rawNfsServer }}
            readOnly: {{ .Values.backup.rawNfsReadOnly }}
        {{- else }}
        - name: {{ template "grafana.fullname" . }}-backup
        {{- if .Values.backup.persistent }}
          persistentVolumeClaim:
            claimName: {{ template "grafana.fullname" . }}-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- end }}	
