{{- if .Values.persistence.gitlabBuilds.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-builds
  annotations:
  {{- if .Values.persistence.gitlabData.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.gitlabBuilds.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabBuilds.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabBuilds.size | quote }}
{{- end }}
