apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ## This is used by GitLab Omnibus as the primary means of configuration.
  ## ref: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
  ##
  gitlab_omnibus_config: |
    external_url '{{ default "" .Values.externalUrl }}'
    postgresql['enable'] = false;
    gitlab_rails['db_host'] = ENV['DB_HOST'];
    gitlab_rails['db_password'] = ENV['DB_PASSWORD'];
    gitlab_rails['db_username'] = ENV['DB_USER'];
    gitlab_rails['db_database'] = '{{ .Values.postgresql.postgresDatabase }}';
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'
    gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
    gitlab_rails['smtp_address'] = '{{ default "" .Values.smtp.address }}'
    gitlab_rails['smtp_domain'] = '{{ default "" .Values.smtp.domain }}'
    gitlab_rails['smtp_port'] = '{{ default "25" .Values.smtp.port }}'
    gitlab_rails['smtp_authentication'] = false
    gitlab_rails['smtp_enable_starttls_auto'] = true
    redis['enable'] = false;
    gitlab_rails['redis_host'] = ENV['REDIS_HOST'];
    gitlab_rails['redis_port'] = '6379'
    gitlab_rails['initial_shared_runners_registration_token'] = "token"

    gitlab_rails['registry_enabled'] = true
    gitlab_rails['registry_host'] = "registry.gitlab.example.com"
    gitlab_rails['registry_port'] = "5005"
    gitlab_rails['registry_api_url'] = "http://localhost:5000"
    gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"
    gitlab_rails['registry_issuer'] = "omnibus-gitlab-issuer"

    gitlab_rails['registry_enabled'] = true
    gitlab_rails['registry_host'] = "{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"
    gitlab_rails['registry_api_url'] = "http://{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"
    registry['registry_http_addr'] = "{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"

    gitlab_rails['initial_root_password'] = 'password'
    gitlab_rails['usage_ping_enabled'] = false
    gitlab_monitor['enable'] = true
    prometheus['enable'] = true
    prometheus_monitoring['enable'] = true
    prometheus['monitor_kubernetes'] = false
    prometheus['listen_address'] = '0.0.0.0:9090'
    node_exporter['enable'] = false
    nginx['listen_https'] = false
    nginx['listen_port'] = 80
    gitlab_rails['rack_attack_git_basic_auth'] = { 'enabled' => false }
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = "mail.obi.com"
    gitlab_rails['smtp_port'] = 25
    gitlab_rails['smtp_domain'] = "mail.obi.com"
    gitlab_rails['smtp_authentication'] = false
    gitlab_rails['smtp_tls'] = false;
    gitlab_rails['smtp_openssl_verify_mode'] = 'none'
    gitlab_rails['smtp_enable_starttls_auto'] = false
    gitlab_rails['smtp_ssl'] = false
    gitlab_rails['smtp_force_ssl'] = false
