apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ## This is used by GitLab Omnibus as the primary means of configuration.
  ## ref: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
  ##
  gitlab_omnibus_config: |
    external_url '{{ default "" .Values.externalUrl }}'
    postgresql['enable'] = false;
    gitlab_rails['db_host'] = ENV['DB_HOST'];
    gitlab_rails['db_password'] = ENV['DB_PASSWORD'];
    gitlab_rails['db_username'] = ENV['DB_USER'];
    gitlab_rails['db_database'] = '{{ .Values.postgresql.postgresDatabase }}';
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'
    redis['enable'] = false;
    gitlab_rails['redis_host'] = ENV['REDIS_HOST'];
    gitlab_rails['redis_port'] = '6379'
    gitlab_rails['initial_shared_runners_registration_token'] = "token"
    gitlab_rails['registry_enabled'] = true
    gitlab_rails['registry_host'] = "{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"
    gitlab_rails['registry_api_url'] = "http://{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"
    registry['registry_http_addr'] = "{{ default "registry.paas-prod01.obi.dmz" .Values.registryHost }}"
    gitlab_rails['initial_root_password'] = 'password'
    gitlab_rails['usage_ping_enabled'] = false
    gitlab_monitor['enable'] = true
    prometheus_monitoring['enable'] = true
    prometheus['listen_address'] = '0.0.0.0:9090'
    node_exporter['enable'] = false
