apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if default "" .Values.gitlabRootPassword }}
  gitlab-root-password: {{ default "ignore" .Values.gitlabRootPassword | b64enc | quote }}
  {{ end }}
  db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
