apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nginx.fullname" . }}-route
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kolihub.io/{{ .Values.nginx.host }}: primary
spec:
  rules:
  - host: {{ .Values.nginx.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "nginx.fullname" . }}
          servicePort: {{ .Values.nginx.service.port }}
