apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "portus.fullname" . }}
  labels:
    name: {{ template "portus.fullname" . }}
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.portus.replicas }}
  selector:
    matchLabels:
      name: {{ template "portus.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "portus.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: "portus"
          image: "{{ .Values.portus.image.repository }}:{{ .Values.portus.image.tag }}"
          imagePullPolicy: {{ .Values.portus.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "openssl genrsa -out /secrets/portus.key 3072;/init"]
          ports:
            - containerPort: {{ .Values.portus.service.port }}
          env:
            - name: PORTUS_MACHINE_FQDN_VALUE
              value: {{ template "portus.fullname" . }}
            - name: PORTUS_DB_ADAPTER
              value: {{ .Values.portus.dbAdapter }}
            - name: PORTUS_DB_HOST
              value: {{ .Values.portus.dbHost }}
            - name: PORTUS_DB_DATABASE
              value: {{ .Values.portus.dbDatabase }}
            - name: PORTUS_DB_USERNAME
              value: {{ .Values.portus.dbUsername }}
            - name: PORTUS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_PRODUCTION_PASSWORD
            - name: PORTUS_KEY_PATH
              value: "/secrets/portus.key"
            - name: PORTUS_PUMA_HOST
              value: {{ template "portus.fullname" . }} # :{{ .Values.portus.service.port }}
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: PORTUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_PASSWORD
            - name: PORTUS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_SECRET_KEY_BASE
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: certificates
              mountPath: /certificates
            - name: config
              mountPath: /srv/Portus/config/config-local.yml
              subPath: etc/config-local.yml
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: cacerts
              readOnly: true
            - mountPath: /etc/pki
              name: pki
              readOnly: true
        - name: "portus-background"
          image: "{{ .Values.portus.image.repository }}:{{ .Values.portus.image.tag }}"
          imagePullPolicy: {{ .Values.portus.image.pullPolicy }}
          env:
            - name: PORTUS_BACKGROUND
              value: "true"
            - name: PORTUS_DB_ADAPTER
              value: {{ .Values.portus.dbAdapter | quote }}
            - name: PORTUS_DB_HOST
              value: {{ .Values.portus.dbHost }}
            - name: PORTUS_DB_DATABASE
              value: {{ .Values.portus.dbDatabase }}
            - name: PORTUS_DB_USERNAME
              value: {{ .Values.portus.dbUsername }}
            - name: PORTUS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_PRODUCTION_PASSWORD
            - name: PORTUS_KEY_PATH
              value: "/secrets/portus.key"
            - name: PORTUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_PASSWORD
            - name: PORTUS_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ template "portus.fullname" . }}
                  key: PORTUS_SECRET_KEY_BASE
          resources:
{{ toYaml .Values.portus.background.resources | indent 12 }}
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: certificates
              mountPath: /certificates
            - mountPath: /etc/ssl/certs
              name: cacerts
              readOnly: true
            - mountPath: /etc/pki
              name: pki
              readOnly: true
      volumes:
        - name: secrets
          emptyDir: {}
        - name: certificates
          emptyDir: {}
        - hostPath:
            path: /etc/ssl/certs
          name: cacerts
        - hostPath:
            path: /etc/pki
          name: pki
        - name: config
          configMap:
            name: {{ template "portus.fullname" . }}
            items:
              - key: config
                path: etc/config-local.yml
