apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: helm-server
  name: helm-server
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helm-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: helm-server
    spec:
      containers:
      - image: "wildbeavers/beaver-deployment-application"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/bin/helm init; /bin/helm serve --address $ENDPOINT_IPADDR:8879 --url $ENDPOINT_URL"]
        name: helm-server
        env:
        - name: ENDPOINT_IPADDR
          value: "0.0.0.0"
        - name: ENDPOINT_URL
          value: "https://helm-registry.example.com"
        ports:
        - containerPort: 8879
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: helm-server
  name: helm-server
  namespace: tools
spec:
  ports:
  - nodePort:
    port: 8879
    protocol: TCP
    targetPort: 8879
  selector:
    run: helm-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-routes
  namespace: tools
  annotations:
    kolihub.io/helm-registry.example.com: primary
spec:
  rules:
  - host: helm-registry.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: helm-server
          servicePort: 8879
