{{- if .Values.deployment.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "{{ .Values.service.internalPort }}"
        prometheus.io/scrape: "{{ .Values.metrics.enabled }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
      labels:
        app: "{{ template "fullname" . }}"
    spec:
      containers:
      - name: "{{ template "fullname" . }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key | upper }}
          value: {{ $val | quote }}
        {{- end}}
        {{- range $key, $val := .Values.secrets }}
        - name: {{ $key | upper }}
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: {{ $key | upper }}
        {{- end}}
{{- end -}}
