{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: "kong-{{ .Values.ingress.class }}"
{{- end }}
{{- if .Values.ingress.prefunction.enabled }}
    pre-function.plugin.konghq.com: "{{ template "fullname" . }}-pre-functions"
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: "{{ template "fullname" . }}"
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
