apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql.fullname" . }}-initdb
  labels:
    app: {{ template "postgresql.fullname" . }}-initdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  01_create_production.sql: |
    CREATE DATABASE user;
