---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: camptocamp/pghoard
            env:
              - name: PGHOARD_STORAGE_TYPE
                value: local
              - name: PGHOARD_DIRECTORY
                value: /tmp/
              - name: PG_HOST
                value: {{ template "postgresql.fullname" . }}
              - name: PG_PORT
                value: {{ .Values.service.port }}
              - name: PG_USER
                value: {{ default "postgres" .Values.postgresUser | quote }}
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "postgresql.fullname" . }}
                    key: postgres-password
          restartPolicy: OnFailure
