apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb.fullname" . }}-backupconfig
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  clenup-old-files.sh: |
    #!/bin/bash

    find {{ .Values.backup.directory }} -type f -mindepth 1 -mtime +{{ .Values.backup.deleteOldFilesAfter }} -delete

