apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kong.fullname" . }}-ui-route
  annotations:
    kolihub.io/{{ template "kong.name" . }}-ui.stage01.obi.dmz: primary
spec:
  rules:
  - host: {{ template "kong.name" . }}-ui.stage01.obi.dmz
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "kong.fullname" . }}-ui
          servicePort: 8080
