{{- if .Values.kongui.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kong.fullname" . }}-ui-route
spec:
  rules:
  - host: {{ template "kong.name" . }}-ui.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "kong.fullname" . }}-ui
          servicePort: 8080
{{- end -}}
