apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-proxy-http
  annotations:
    {{- range $key, $value := .Values.proxy-http.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.proxy-http.type }}
  {{- if and (eq .Values.proxy-http.type "LoadBalancer") .Values.proxy-http.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.loadBalancerIP }}
  {{- end }}
  ports:
  - name: kong-proxy-http
    port: {{ .Values.proxy-http.servicePort }}
    targetPort: {{ .Values.proxy-http.containerPort }}
  {{- if (and (eq .Values.proxy-http.type "NodePort") (not (empty .Values.proxy-http.nodePort))) }}
    nodePort: {{ .Values.proxy-http.nodePort }}
  {{- end }}
    protocol: TCP
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
