apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-proxyhttp
  annotations:
    {{- range $key, $value := .Values.proxyhttp.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.proxyhttp.type }}
  {{- if and (eq .Values.proxyhttp.type "LoadBalancer") .Values.proxyhttp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.loadBalancerIP }}
  {{- end }}
  ports:
  - name: kong-proxyhttp
    port: {{ .Values.proxyhttp.servicePort }}
    targetPort: {{ .Values.proxyhttp.containerPort }}
  {{- if (and (eq .Values.proxyhttp.type "NodePort") (not (empty .Values.proxyhttp.nodePort))) }}
    nodePort: {{ .Values.proxyhttp.nodePort }}
  {{- end }}
    protocol: TCP
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
