apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-storage
  namespace: gitlab
  {{- if (eq .Values.provider "gke") }}
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitlabConfigStorageSize }}
