apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-rails-storage
  namespace: gitlab
  {{- if (eq .Values.provider "gke") }}
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitlabRailsStorageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
  {{- if (eq .Values.provider "gke") }}
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitlabRegistryStorageSize }}
