{{- if (eq .Values.provider "gke") }}
kind: StorageClass
apiVersion: {{ if .Capabilities.APIVersions.Has "storage.k8s.io/v1" }}storage.k8s.io/v1{{ else }}storage.k8s.io/v1beta1{{ end }}
metadata:
  name: fast
  namespace: gitlab
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
{{- if eq .Values.provider "gke" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end }}
{{- end }}
