{{- if .Values.service.enabled -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
  annotations:
    kolihub.io/{{ .Values.service.hostname }}: primary
spec:
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.application.name }}
          servicePort: {{ .Values.service.externalPort }}

{{- end -}}
